### ISSUE TITLE
kebab-case for files in /doc/

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/best-practices#7]
kebab-case for naming files in `/doc/`.

- [ ] Document as best practice.
- [ ] Rename files across repositories.

**Comment by jgvictores** [comment]
Related to https://github.com/roboticslab-uc3m/installation-guides/issues/7 and https://github.com/roboticslab-uc3m/best-practices/issues/5

**Comment by jgvictores** [comment]
Small announcement: as https://github.com/roboticslab-uc3m/installation-guides/issues/7 has been closed, we must update links across repos.
I'll be working on all the TEO repos listed on [teo-software-manual](https://github.com/roboticslab-uc3m/teo-software-manual/tree/ff810f7d1ab5c3d59322fafb55f616986c6f1151)

@PeterBowman Could you please update ASIBOT and AMOR links?
@RaulFdzbis  Could you please check xgnitive links?
@David-Estevez Could you please check textiles links (I think these haven't changed)?

**Comment by PeterBowman** [comment]
ASIBOT and AMOR repos done.

**Comment by RaulFdzbis** [comment]
Done for xgnitive in  https://github.com/roboticslab-uc3m/xgnitive/commit/8050a0a4c0ee1682eabb86e60496732791a829fa

**Comment by David-Estevez** [comment]
Nothing to do for textiles.

I also added this preference to [best-practices](https://github.com/roboticslab-uc3m/best-practices) (https://github.com/roboticslab-uc3m/best-practices/commit/90fa0e178743440946cc5de90d45ecc83b1ea609). Please reopen the issue if any of you thinks something is still missing.

**Comment by jgvictores** [comment]
@David-Estevez Thanks a lot for this!
